//! Parity-golden tests: the Rust port must reproduce the TypeScript
//! implementation byte-exactly (docs/DESIGN.md: Rust port (transition
//! record)). Method: load parity/goldens/*.json — generated by
//! `bun scripts/parity-goldens.ts` from the TS functions under port, and
//! pinned against drift by the `test` CI job — and assert every recorded
//! input/output pair against the ported Rust function.

use std::path::Path;

use beam::util::digest::{file_sha256, file_sha256_chunked, tree_manifest, tree_sha256};
use beam::util::shell::{shjoin, shq, shq_remote_path};

fn golden(name: &str) -> serde_json::Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../parity/goldens")
        .join(name);
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|err| panic!("parse {}: {err}", path.display()))
}

fn fixture_tree() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../parity/fixtures/tree")
}

#[test]
fn shq_matches_typescript_golden() {
    let cases = golden("shell-quoting.json");
    for case in cases["shq"].as_array().expect("shq corpus is an array") {
        let input = case["input"].as_str().expect("input is a string");
        let expected = case["output"].as_str().expect("output is a string");
        assert_eq!(shq(input), expected, "shq({input:?})");
    }
}

#[test]
fn shq_remote_path_matches_typescript_golden() {
    let cases = golden("shell-quoting.json");
    for case in cases["shqRemotePath"]
        .as_array()
        .expect("remote corpus is an array")
    {
        let input = case["input"].as_str().expect("input is a string");
        let expected = case["output"].as_str().expect("output is a string");
        assert_eq!(
            shq_remote_path(input),
            expected,
            "shq_remote_path({input:?})"
        );
    }
}

#[test]
fn shjoin_matches_typescript_golden() {
    let cases = golden("shell-quoting.json");
    for case in cases["shjoin"].as_array().expect("argv corpus is an array") {
        let argv: Vec<&str> = case["argv"]
            .as_array()
            .expect("argv is an array")
            .iter()
            .map(|arg| arg.as_str().expect("argv entries are strings"))
            .collect();
        let expected = case["output"].as_str().expect("output is a string");
        assert_eq!(shjoin(&argv), expected, "shjoin({argv:?})");
    }
}

#[test]
fn file_sha256_matches_typescript_golden() {
    let cases = golden("digest.json");
    let tree = fixture_tree();
    let one_shot = tree.join("one-shot.txt");
    let expected = cases["oneShot"]["sha256"].as_str().expect("oneShot.sha256");
    assert_eq!(file_sha256(&one_shot).expect("hash one-shot"), expected);

    let multi_chunk = tree.join("../multi-chunk.txt");
    let multi_chunk = multi_chunk
        .canonicalize()
        .unwrap_or_else(|err| panic!("canonicalize {}: {err}", multi_chunk.display()));
    for result in cases["multiChunk"]["results"]
        .as_array()
        .expect("results is an array")
    {
        let chunk_bytes = result["chunkBytes"]
            .as_u64()
            .expect("chunkBytes is a number") as usize;
        let expected = result["sha256"].as_str().expect("result sha256");
        let actual = file_sha256_chunked(&multi_chunk, chunk_bytes).expect("hash multi-chunk");
        assert_eq!(actual, expected, "file_sha256_chunked({chunk_bytes})");
    }
}

#[test]
fn tree_sha256_matches_typescript_golden() {
    let cases = golden("digest.json");
    let expected = cases["treeSha256"].as_str().expect("treeSha256");
    assert_eq!(tree_sha256(&fixture_tree()).expect("hash tree"), expected);
}

#[test]
fn tree_manifest_matches_typescript_golden() {
    let cases = golden("digest.json");
    let expected: Vec<beam::util::digest::TreeManifestEntry> =
        serde_json::from_value(cases["treeManifest"].clone()).expect("manifest shape");
    let actual = tree_manifest(&fixture_tree()).expect("walk tree");
    assert_eq!(actual, expected);
}
